### ISSUE TITLE
No pip install

### ISSUE THREAD

**Issue by grudloff** [zealberth/lssvr#5]
Hey, it seems the project isn't available through pip install!

**Comment by zealberth** [comment]
Oh, i'm sorry, I will fix this. Thanks!

**Comment by grudloff** [comment]
Thanks!

**Comment by zealberth** [comment]
Done, @grudloff 
https://pypi.org/project/lssvr/

**Comment by grudloff** [comment]
Thanks! Is there any easy way to bypass the python^3.8 requirement to install on google colab that currently has python 3.7.10?

**Comment by zealberth** [comment]
Hi, @grudloff ! 

Try this into your colab notebook:

![image](https://user-images.githubusercontent.com/22925458/116281490-28e92880-a760-11eb-96d7-a6e5095bd03e.png)

[I think that is better I change the minimum requirements for this package... hehehe]

**Comment by grudloff** [comment]
Relaxing the constraint from pip cli seems impossible. So it looks like git clone is the only option, though I came to a solution that maintains the same syntax for importing.
```
!git clone https://github.com/zealberth/lssvr
!mv lssvr/lssvr lssvr_temp 
!rm lssvr -r 
!mv lssvr_temp lssvr
```
But changing the minimum requirements may be better :grimacing:

**Comment by zealberth** [comment]
Nice :)

**Comment by grudloff** [comment]
Found an even better solution.
```python
!pip install git+https://github.com/zealberth/lssvr.git
```
This has the added advantage of installing the last version!

**Comment by grudloff** [comment]
@zealberth maybe it is a good idea to add

> Found an even better solution.
> 
> ```python
> !pip install git+https://github.com/zealberth/lssvr.git
> ```
> 
> This has the added advantage of installing the last version!

@zealberth maybe it is a good idea to add this option to the readme to install the latest version?
