### ISSUE TITLE
Support for multidimensional target

### ISSUE THREAD

**Issue by grudloff** [zealberth/lssvr#7]
Hey! I made some modifications to my fork to allow for multidimensional targets! Could you take some time to review if they are sound? As I don't fully understand the code yet. The commit with the changes is [here](https://github.com/grudloff/lssvr/commit/5efed8c01fa9f476a3e685cbd3dd3aadc230a33f).

I am particularly interested in the reason behind the `.ravel()` on line 57. I don't see the effect of it, as in your implementation `t` is a one-dimensional vector.

I am working on a simulation dataset and the results are sound. If you want I could share the use case.

**Comment by zealberth** [comment]
Thank you for your contribution, @grudloff ! 
I will see your commit soon and then talk with you about it.

About the `.ravel()`, I don't remember why I did this, but I think that I used this to solve some problem in my data. Of course, my fault that the data wasn't good, hehe. I think that you could remove this without any problem. :)

And I really appreciate if you could share, thanks!

**Comment by grudloff** [comment]
Great! Looking forward to your feedback.

PD: The parameter C is the regularization, right?

**Comment by zealberth** [comment]
@grudloff yes, C is the regularization parameter. :) 

Your commit sounds good to me. You can send a PR.
